#!/bin/bash

set -e

# Install Homebrew (do this manually before running this script for now)
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install General Packages
brew install git bash bash-completion scmpuff

# Install Java Packages
brew install gradle maven

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

# Install yarn
brew install yarn

# Install Bash Config Files
git clone https://github.com/gyrfalcon/bin.git ~/bin
git clone https://github.com/gyrfalcon/init-new-mac.git ~/.mac-config
cat > ~/.bash_aliases <<EOF
. ~/.mac-config/bash-config-files/bash_aliases
EOF
cat > ~/.bash_env <<EOF
. ~/.mac-config/bash-config-files/bash_env
EOF
ln -s ~/.mac-config/bash-config-files/bash_profile ~/.bash_profile
ln -s ~/.mac-config/bash-config-files/gitconfig ~/.gitconfig
ln -s ~/.mac-config/bash-config-files/gitignore ~/.gitignore
ln -s ~/.mac-config/bash-config-files/vimrc ~/.vimrc

# Reload profile
. ~/.bash_profile

# Install nodejs
nvm install v14
nvm install v16

# Misc
mkdir ~/Development

# Set installed bash as available shell and configure it as the user's shell
sudo sh -c 'echo /usr/local/bin/bash >> /etc/shells'
chsh -s /usr/local/bin/bash

echo '*****************************'
echo ' This Mac is now set up.'
echo ' Close this terminal window'
echo ' and open a new one to get'
echo ' started.'
echo '*****************************'
